<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\..\..\libs\Kira.EF.DependencyInjection\Kira.EF.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\..\..\libs\Kira.UseCases.DI\Kira.UseCases.DI.csproj" />
    <ProjectReference Include="..\Kira.Security.Core\Kira.Security.Core.csproj" />
    <ProjectReference Include="..\Kira.Security.Infrastructure.Caching\Kira.Security.Infrastructure.Caching.csproj" />
    <ProjectReference Include="..\Kira.Security.Infrastructure.Persistence\Kira.Security.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\Kira.Security.Infrastructure\Kira.Security.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Authentication\Kira.Security.Authentication.Bootstrap\Kira.Security.Authentication.Bootstrap.csproj" />
    <ProjectReference Include="..\Modules\Identity\Kira.Security.Identity.Bootstrap\Kira.Security.Identity.Bootstrap.csproj" />
    <ProjectReference Include="..\Modules\Management\Kira.Security.Management.Bootstrap\Kira.Security.Management.Bootstrap.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Serialization.SystemTextJson" />
  </ItemGroup>

</Project>
